version: "3.7"

services:
    web:
        build: .
        command: gunicorn caserepo.wsgi:application --bind 0.0.0.0:80
        environment:
            - DB_USER=${DB_USER}
            - DB_NAME=${DB_NAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - PRODUCTION_SERVER=${PRODUCTION_SERVER}
            - DJANGO_SECRETKEY=${DJANGO_SECRETKEY}
        ports:
            - "80:80"