version: "3.7"

services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:80
        environment:
            - DB_USER=${DB_USER}
            - DB_NAME=${DB_NAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - PRODUCTION_SERVER=${PRODUCTION_SERVER}
        ports:
            - "80:80"