# Generated by Django 3.2.5 on 2021-07-19 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitedDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=50)),
                ('doc_title', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'cited_docs',
            },
        ),
        migrations.CreateModel(
            name='FieldTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_tag', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'field_tags',
            },
        ),
        migrations.CreateModel(
            name='Judges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_name', models.CharField(max_length=100)),
                ('judge_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'judges',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cite_name', models.CharField(max_length=50)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseapi.citeddocs')),
            ],
            options={
                'db_table': 'citations',
            },
        ),
        migrations.CreateModel(
            name='CaseMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('document_title', models.CharField(max_length=100, null=True)),
                ('case_name', models.CharField(max_length=100, null=True)),
                ('doc_id', models.CharField(max_length=25)),
                ('doc_type', models.CharField(max_length=50, null=True)),
                ('case_id', models.CharField(max_length=25, null=True)),
                ('outcome', models.CharField(max_length=50, null=True)),
                ('docket_number', models.CharField(max_length=50, null=True)),
                ('self_cite', models.CharField(max_length=75, null=True)),
                ('judges', models.ManyToManyField(to='caseapi.Judges')),
            ],
            options={
                'db_table': 'case_meta',
            },
        ),
    ]
