# Generated by Django 3.2.5 on 2021-07-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseapi', '0002_auto_20210719_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemeta',
            name='docket_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
