# Generated by Django 3.2.5 on 2021-08-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseapi', '0005_auto_20210810_0131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='USCaseMeta',
            new_name='USCircuitCaseMeta',
        ),
        migrations.AlterField(
            model_name='casemeta',
            name='case_id',
            field=models.CharField(blank=True, default='00000', max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='casemeta',
            name='case_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casemeta',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casemeta',
            name='doc_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casemeta',
            name='doc_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='casemeta',
            name='docket_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casemeta',
            name='judges',
            field=models.ManyToManyField(blank=True, to='caseapi.Judges'),
        ),
        migrations.AlterField(
            model_name='casemeta',
            name='outcome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casemeta',
            name='self_cite',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='casemeta',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='uscircuitcasemeta',
            table='us_circuit_case_meta',
        ),
    ]
