# Generated by Django 3.2.5 on 2021-08-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseapi', '0007_auto_20210818_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(choices=[('CRIMINAL', 'Criminal'), ('FIRST_AMENDMENT', 'First Amendment'), ('CIVIL_RIGHTS', 'Civil Rights'), ('DUE_PROCESS', 'Due Process'), ('PRIVACY', 'Privacy'), ('LABOR_RELATIONS', 'Labor Relations'), ('ECONOMIC_ACTIVITY', 'Economic Activity'), ('REGULATION', 'Regulation'), ('MISCELLANEOUS', 'MISCELLANEOUS')], max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.DeleteModel(
            name='FieldTags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AlterField(
            model_name='judges',
            name='judge_gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='usjudge',
            name='party',
            field=models.IntegerField(blank=True, choices=[(0, 'Democrat'), (1, 'Republican')], null=True),
        ),
        migrations.AddField(
            model_name='casemeta',
            name='tags',
            field=models.ManyToManyField(blank=True, to='caseapi.Tag'),
        ),
    ]
