# Generated by Django 3.2.5 on 2021-08-22 15:38
# DO NOT DELETE THIS MIGRATION WHEN NUKING MIGRATIONS, IT JUST PROVIDES INITIAL DATA

from django.db import migrations

# This migration simply creates the default tags
# Idea from https://docs.djangoproject.com/en/dev/topics/migrations/#data-migrations on using migrations to provide initial data

def create_tags(apps, schema_editor):
    Tag = apps.get_model('caseapi', 'Tag')
    CRIMINAL = 'CRIMINAL'
    FIRST_AMENDMENT = 'FIRST_AMENDMENT'
    CIVIL_RIGHTS = 'CIVIL_RIGHTS'
    DUE_PROCESS = 'DUE_PROCESS'
    PRIVACY = 'PRIVACY'
    LABOR_RELATIONS = 'LABOR_RELATIONS'
    ECONOMIC_ACTIVITY = 'ECONOMIC_ACTIVITY'
    REGULATION = 'REGULATION'
    MISCELLANEOUS = 'MISCELLANEOUS'

    Tag(name=CRIMINAL).save()
    Tag(name=FIRST_AMENDMENT).save()
    Tag(name=CIVIL_RIGHTS).save()
    Tag(name=DUE_PROCESS).save()
    Tag(name=PRIVACY).save()
    Tag(name=LABOR_RELATIONS).save()
    Tag(name=ECONOMIC_ACTIVITY).save()
    Tag(name=REGULATION).save()
    Tag(name=MISCELLANEOUS).save()


class Migration(migrations.Migration):

    dependencies = [
        ('caseapi', '0008_auto_20210822_1537'),
    ]

    operations = [
        migrations.RunPython(create_tags)
    ]
