# Generated by Django 3.2.5 on 2021-08-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseapi', '0009_initial_data_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uscircuitcasemeta',
            name='circuit_num',
        ),
        migrations.AddField(
            model_name='uscircuitcasemeta',
            name='circuit_name',
            field=models.IntegerField(blank=True, choices=[(0, 'Federal Circuit'), (1, '1st Circuit'), (2, '2nd Circuit'), (3, '3rd Circuit'), (4, '4th Circuit'), (5, '5th Circuit'), (6, '6th Circuit'), (7, '7th Circuit'), (8, '8th Circuit'), (9, '9th Circuit'), (10, '10th Circuit'), (11, '11th Circuit'), (12, 'DC Circuit')], null=True),
        ),
    ]
