# Generated by Django 3.2.5 on 2021-08-24 13:01

from django.db import migrations, models
from django.db.migrations.operations.fields import AlterField
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caseapi', '0010_auto_20210822_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeRuling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(blank=True, choices=[(1, 'Concurring'), (0, 'Dissenting')], null=True)),
                ('author', models.BooleanField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseapi.casemeta')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseapi.judges')),
            ],
        ),
        migrations.RemoveField(
            model_name='casemeta',
            name = 'judges',
        ),
        migrations.AddField(
            model_name='casemeta',
            name='judges',
            field=models.ManyToManyField(blank=True, through='caseapi.JudgeRuling', to='caseapi.Judges'),
        ),
    ]
