# Generated by Django 3.2.5 on 2021-08-27 18:15
# DO NOT DELETE THIS MIGRATION WHEN NUKING MIGRATIONS, IT JUST PROVIDES INITIAL DATA

from django.db import migrations

# This migration simply creates the default tags
# Idea from https://docs.djangoproject.com/en/dev/topics/migrations/#data-migrations on using migrations to provide initial data

def create_tags(apps, schema_editor):
    Tag = apps.get_model('caseapi', 'Tag')
    db_alias = schema_editor.connection.alias
    Tag.objects.using(db_alias).delete() # delete all existing tags first
    CRIMINAL = 'CRIMINAL'
    FIRST_AMENDMENT = 'FIRST AMENDMENT'
    CIVIL_RIGHTS = 'CIVIL RIGHTS'
    DUE_PROCESS = 'DUE PROCESS'
    PRIVACY = 'PRIVACY'
    LABOR_RELATIONS = 'LABOR RELATIONS'
    ECONOMIC_ACTIVITY = 'ECONOMIC ACTIVITY'
    REGULATION = 'REGULATION'
    MISCELLANEOUS = 'MISCELLANEOUS'

    Tag(name=CRIMINAL).save()
    Tag(name=FIRST_AMENDMENT).save()
    Tag(name=CIVIL_RIGHTS).save()
    Tag(name=DUE_PROCESS).save()
    Tag(name=PRIVACY).save()
    Tag(name=LABOR_RELATIONS).save()
    Tag(name=ECONOMIC_ACTIVITY).save()
    Tag(name=REGULATION).save()
    Tag(name=MISCELLANEOUS).save()


class Migration(migrations.Migration):

    dependencies = [
        ('caseapi', '0011_auto_20210824_1301'),
    ]

    operations = [
        migrations.RunPython(create_tags)
    ]
