# Generated by Django 3.2.5 on 2021-08-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseapi', '0012_initial_data_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemeta',
            name='doc_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='judgeruling',
            unique_together={('judge', 'case')},
        ),
    ]
