# Generated by Django 3.2.5 on 2021-09-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseapi', '0013_auto_20210827_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judges',
            name='judge_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
