# Generated by Django 3.2.5 on 2021-10-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseapi', '0014_alter_judges_judge_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgeruling',
            name='vote',
            field=models.IntegerField(blank=True, choices=[(0, 'Dissenting'), (1, 'Concurring'), (2, 'Partial')], null=True),
        ),
    ]
